name: Android CI
run-name: ${{ github.actor }} is running CI tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "📋 Running Android CI"
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Run unit tests
      run: ./gradlew test --info
