name: Android CI
run-name: ${{ github.actor }} is running CI tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "📋 Running Android CI"
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Run unit tests
      run: ./gradlew test
